# Generated by Django 2.1.5 on 2019-01-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='班級名稱')),
                ('password', models.CharField(max_length=30, verbose_name='選課密碼')),
                ('teacher_id', models.IntegerField(default=0)),
            ],
        ),
    ]
