# Generated by Django 2.1.5 on 2019-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='lesson',
            field=models.IntegerField(choices=[(1, 'Science科學運算：使用Python3')], default=0, verbose_name='課程名稱'),
        ),
    ]
