# Generated by Django 2.1.2 on 2019-01-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='TWork',
        ),
    ]
