# Generated by Django 2.1.5 on 2019-01-26 09:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20190124_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='twork',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
