# Generated by Django 2.1.5 on 2019-01-27 03:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_twork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twork',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=teacher.models.work_json_default, verbose_name='作業說明'),
        ),
        migrations.AlterField(
            model_name='twork',
            name='title',
            field=models.CharField(max_length=250, verbose_name='作業名稱'),
        ),
    ]
