# Generated by Django 2.1.5 on 2019-01-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(default='')),
                ('url', models.CharField(max_length=250)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessagePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(default=0)),
                ('reader_id', models.IntegerField(default=0)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
