# Generated by Django 2.1.2 on 2019-01-24 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Science1Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(default=0)),
                ('types', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('pic', models.FileField(blank=True, null=True, upload_to='')),
                ('picname', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Science1Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField(default=0)),
                ('question', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Science1Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Science2Json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('model_type', models.IntegerField(default=0)),
                ('json', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Science3Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('lesson', models.IntegerField(default=0)),
                ('typing', models.IntegerField(default=0)),
                ('index', models.IntegerField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(upload_to='')),
                ('helps', models.IntegerField(choices=[(0, '全部靠自己想'), (1, '同學幫一點忙'), (2, '同學幫很多忙'), (3, '老師幫一點忙'), (4, '老師幫很多忙')], default=0)),
                ('code', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Science4Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work3_id', models.IntegerField(default=0)),
                ('bug_types', models.IntegerField(choices=[(0, '程式語法錯誤'), (1, '程式邏輯錯誤'), (2, '其它')], default=0)),
                ('bug', models.TextField(default='')),
                ('improve', models.TextField(default='')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Science4Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('index', models.IntegerField(default=0)),
                ('memo', models.TextField(default='')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
