# Generated by Django 2.1.5 on 2019-01-27 03:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_science1content_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='science2json',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
