# Generated by Django 2.1.2 on 2019-01-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_science2json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='science1content',
            name='edit_new',
            field=models.BooleanField(default=True),
        ),
    ]
