# Generated by Django 2.1.2 on 2019-01-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_science1content_edit_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science1content',
            name='edit_new',
        ),
        migrations.AddField(
            model_name='science1content',
            name='edit_old',
            field=models.BooleanField(default=False),
        ),
    ]
