# Generated by Django 2.1.5 on 2019-02-01 08:15

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
from django.utils import timezone


def migrate_expression(apps, schema_editor):
    Science2Json = apps.get_model("student", "Science2Json")
    items = Science2Json.objects.all()
    for item in items:
        for q in item.data:
            data = item.data[q]
            item.data[q] = [{'expr': data, 'created': timezone.now()}]
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20190129_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science2json',
            name='json',
        ),
        migrations.AlterField(
            model_name='science2json',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.RunPython(migrate_expression),
    ]
