# Generated by Django 2.1.5 on 2019-02-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20190201_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='science1content',
            name='edit_id',
            field=models.IntegerField(default=0),
        ),
    ]
