# Generated by Django 2.1.5 on 2019-02-03 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_science1content_edit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='science1content',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
