# Generated by Django 2.1.5 on 2019-02-12 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_science1content_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='science1content',
            name='publication_date_old',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
