# Generated by Django 2.1.5 on 2019-02-12 22:06

from django.db import migrations, models
import django.utils.timezone
import json

def migrate_expression(apps, schema_editor):
    Science2Json = apps.get_model("student", "Science2Json")
    items = Science2Json.objects.all()
    for item in items:
        modified = False
        for q in item.data:
            for e in item.data[q]:
                if type(e['expr']) == type(str()):
                    e['expr'] = json.loads(e['expr'])
                    modified = True
        if modified:
            item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_science1content_publication_date_old'),
    ]

    operations = [
        migrations.RunPython(migrate_expression),
    ]
